import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import Context from "@/context/Context";

export const metadata = {
  title: "Time Kepeer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Context>
            {children}
          </Context>
        </AuthProvider>
      </body>
    </html>
  );
}
