import { Nav } from "@/components";
import "./globals.css";
import TopNav from "@/components/Nav/TopNav";

export const metadata = {
  title: "Time Kepeer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        <Nav />
        {children}
      </body>
    </html>
  );
}
