import './globals.css'
import localFont from "next/font/local"

const oswadfont = localFont({src:[
  
]})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={oswadfont.className}>{children}</body>
    </html>
  )
}
