export const carouseldata = [
    {
        title : "Small Pleasures From Time keeper",
        productImg : "/images/slider3_slide1_01-copyright (1).png",
        banner : "/images/slider3_slide1_02-copyright.jpg",
        description : "we transparently build high-quality minimal watches from the finest components and materials"
    },
    {
        title : "Small Pleasures From Time keeper",
        productImg : "/images/slider3_slide1_01-copyright (1).png",
        banner : "/images/slider3_slide2_02-copyright.png",
        description : "we transparently build high-quality minimal watches from the finest components and materials"
    },
]