const prodcutData = [
    {
        id : 1,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 2,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4.5,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 3,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 4,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 5,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 6,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 7,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 8,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 9,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 10,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 11,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
    {
        id : 12,
        img : "/images/slider3_slide2_02-copyright.png",
        title : "FAAST  TRACK ANALOG GOLDEN DEAL MEN'S WATCH",
        ratting : 4,
        price : 2400.00,
        description : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiati.",
        catagory : "Gold Watches",
        brand : "LONGINES",
        off : 40,
    },
]

export default prodcutData;